PANGOLINDIR=1
EXITDIR=UP
MAPSIZE=20;14
/////////////       
XXXXXXXXXXXXXXXXXXXX              
XXXXXXXXXXXXXXXX E X
X          XXXXX   X
X          XXXXX   X 
X   O    XXXXXXX   X
X        XXXXXXX   X
X        XXXXXXX   X
X   S    XXXXXXX   X
X        XXXXXXX   X
X                  X 
X                  X
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
