PANGOLINDIR=0
EXITDIR=DOWN
MAPSIZE=20;14
/////////////       
XXXXXXXXXXXXXXXXXXXX              
XXXXXXXXXXXXXXXX   X
X                  X
XXXXX              X 
XXXXX              X
X                  X
X     XXXX    XX   X
X     XXXX    XX   X
X     XXXX    XX   X
X     XXXX    XX   X 
X     XXXX    XX  EX
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
